# set base image
FROM python:slim-bullseye


# maintainer: SsongIU
MAINTAINER SsongIU


# frontend setting
ENV DEBIAN_FRONTEND noninteractive


# install apt-utils
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils \
    && rm -rf /var/lib/apt/lists/*


# install dependencies program
RUN apt-get update && apt-get install -y --no-install-recommends \
    locales wget curl git unzip \
    python3-tk \
    gcc g++ \
    openjdk-11-jdk-headless \
    && rm -rf /var/lib/apt/lists/*


# locale setting
RUN localedef -f UTF-8 -i ko_KR ko_KR.UTF-8
ENV LANG=ko_KR.UTF-8 \
    LANGUAGE=ko_KR.UTF-8 \
    LC_ALL=ko_KR.UTF-8 \
    PYTHONIOENCODING=utf-8


# install chrome and chrome-driver
WORKDIR /usr/src
RUN apt-get -y update \
    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt-get -y install ./google-chrome-stable_current_amd64.deb \
    && wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/` curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip \
    && mkdir chrome \
    && unzip /tmp/chromedriver.zip chromedriver -d /usr/src/chrome \
    && rm -rf ./google-chrome-stable_current_amd64.deb


# hangul fonts setting
RUN apt-get update && apt-get install -y --no-install-recommends \
    fontconfig \
    fonts-nanum \
    && fc-cache -fv \
    && rm -rf /var/lib/apt/lists/*


# make bind mount dir and copy dir
RUN mkdir /workspace \
    $$ mkdir /copy
WORKDIR /copy


# copy the dependencies file to the working directory
COPY requirements.txt .



# install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt
