---
title: R_Study
date: 2022-08-11
---
```{r include=FALSE}
knitr::opts_chunk$set(message = FALSE, echo = FALSE)
```


# 두 집단의 차이 검정

## 평균검정: t-test
    - 단일표본, 독립표본, 대응표본

```{r}
data(sleep)
str(sleep)
```
```{r}
library(tidyr)
wide.df <- spread(sleep, key = group, value = extra)
summary(wide.df)
```
```{r}
tapply(sleep$extra,
    INDEX = list(sleep$group),
    FUN = mean
)
```
```{r}
t.test(extra ~ group, data = sleep, paired = TRUE)
```

## 독립성검정과 적합성검정

```{r}
v <- rchisq(n = 10000, df = 1)
hist(v, col = "orange", prob = TRUE)
x <- seq(0, 15, length = 200)
curve(dchisq(x, df = 1), 0, 15, add = TRUE, col = "red", lwd = 2, lty = 1)
curve(dchisq(x, df = 5), 0, 15, add = TRUE, col = "tomato", lwd = 2, lty = 1)
curve(dchisq(x, df = 10), 0, 15, add = TRUE, col = "steelblue", lwd = 2, lty = 1)
```
```{r}
qchisq(p = 0.95, df = 1)
pchisq(q = 3.841459, df = 1)
pchisq(q = 5, df = 1, lower.tail = FALSE)
```

### 카이스퀘어 과정 따라가기

```{r}
mt <- matrix(c(1443, 151, 47, 1781, 312, 135), nrow = 3)
mt
```
```{r}
df <- data.frame(mt)
str(df)
colnames(df) <- c("With", "Without")
rownames(df) <- c("경상", "중상", "사망")
df
```
```{r}
oij <- c(1443, 1781, 151, 312, 47, 135)
eij <- c(1367, 1855.9, 196.9, 267.4, 77.1, 104.7)
cs.value <- sum((oij - eij)^2 / eij)
cs.value
```

```{r}
Titanic
tb <- margin.table(Titanic, margin = c(4, 1))
tb
chisq.test(tb)
```
