# set base image
FROM jupyter/datascience-notebook


# maintainer: SsongIU
MAINTAINER SsongIU


# hangul fonts setting
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    locales \
    language-pack-ko \
    fontconfig \
    fonts-nanum \
    fonts-naver-d2coding \
    && fc-cache -fv \
    && rm -fr ~/.cache/matplotlib \
    && rm -rf /var/lib/apt/lists/*


# locale setting
ENV LANG=ko_KR.UTF-8 \
    LANGUAGE=ko_KR.UTF-8 \
    LC_ALL=ko_KR.UTF-8 \
    PYTHONIOENCODING=utf-8


# install requirments
RUN mkdir /copy
WORKDIR /copy
COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt


USER ${NB_UID}
RUN mamba install --quiet --yes \
    'r-languageserver' \
    'r-httpgd' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"


# Switch back to jovyan to avoid accidental container runs as root
USER ${NB_UID}
WORKDIR "${HOME}"
