project:
  type: website

website:
  title: "team2_orange"
  navbar:
    left:
      - href: index.qmd
        text: Team2
      - href: naryoung.qmd
        text: naryoung
      - href: chaebeom.qmd
        text: chaebeom
      - href: yeongchan.qmd
        text: yeongchan
      - href: younghyo.qmd
        text: younghyo
      - href: inuk.qmd
        text: inuk
      - href: doyoung.qmd
        text: doyoung



