project:
  type: website

website:
  title: "team2_orange"
  navbar:
    left:
      - href: index.qmd
        text: Team2
      - about.qmd
      - naryoung.qmd
      - chaebeam.qmd
      - yeongchan.qmd
      - younghyo.qmd
      - inuk.qmd
      - doyoung.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



